name: .NET CI

on:
    push:
        branches: [ "master", "main" ]
    pull_request:
        branches: [ "master", "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              continue-on-error: true
              run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage

            - name: List files
              run: ls -R ./coverage

            - name: ReportGenerator
              if: always()
              uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
              with:
                  reports: 'coverage/**/*.xml'
                  targetdir: 'coveragereport'
                  reporttypes: 'Html;HtmlSummary'

            - name: Upload coverage report artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: code-coverage-report
                  path: coveragereport
